[project]
name = "probtm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.0",
    "equinox>=0.11.8",
    "jax>=0.4.34",
    "jaxtyping>=0.2.34",
    "readchar>=4.2.0",
]
